### ISSUE TITLE
No module named ui.GUI

### ISSUE THREAD

**Issue by gcgloriachan** [BioinformaticsLabAtMUN/Promotech#16]
Hi Team, 

After I have tried to run the genomic parse "python promotech.py -pg -ts 20000 -f RP/promotech_data/dataset/GCF_000021865.1_ASM2186v1_genomic.fasta -o results" I got a error that says "No module named ui.GUI' even though I have put a folder of the ui files in the same directory as the python script. Any ideas what might have caused this?:

"Traceback (most recent call last):
  File "promotech.py", line 5, in <module>
    from ui.GUI import Promotech_UI
ModuleNotFoundError: No module named 'ui.GUI'

**Comment by BioinformaticsLabAtMUN** [comment]
Hi,

You need to install the ui package https://pypi.org/project/ui/ and also make sure to clone the project.

**Comment by fraseraj** [comment]
Hi,
I'm having an issue when trying to predict promoter sequences using the parsed sequence in whole-genome mode. The error message is below. I have checked the models directory and RF-HOT.model is in there. Thanks in advance!

Traceback (most recent call last):
  File "/home/frasera/Promotech/promotech.py", line 91, in <module>
    threshold       = args.threshold
  File "/home/frasera/Promotech/genome/process_genome.py", line 175, in predictGenomeSequences
    Path(model_path).stat().st_size  / 1000000
  File "/home/frasera/miniconda3/envs/promotech_env/lib/python3.6/pathlib.py", line 1158, in stat
    return self._accessor.stat(self)
  File "/home/frasera/miniconda3/envs/promotech_env/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: 'models/RF-HOT.model'

**Comment by pandaspa** [comment]
> Hi, I'm having an issue when trying to predict promoter sequences using the parsed sequence in whole-genome mode. The error message is below. I have checked the models directory and RF-HOT.model is in there. Thanks in advance!
> 
> Traceback (most recent call last): File "/home/frasera/Promotech/promotech.py", line 91, in threshold = args.threshold File "/home/frasera/Promotech/genome/process_genome.py", line 175, in predictGenomeSequences Path(model_path).stat().st_size / 1000000 File "/home/frasera/miniconda3/envs/promotech_env/lib/python3.6/pathlib.py", line 1158, in stat return self._accessor.stat(self) File "/home/frasera/miniconda3/envs/promotech_env/lib/python3.6/pathlib.py", line 387, in wrapped return strfunc(str(pathobj), *args) FileNotFoundError: [Errno 2] No such file or directory: 'models/RF-HOT.model'

I have same issue,too.Can you tell me how do you slove this?
