### ISSUE TITLE
Running Promtech on SuperContig Level Assembly

### ISSUE THREAD

**Issue by Rohit-Satyam** [BioinformaticsLabAtMUN/Promotech#2]
Hi Developers!!

I planned using Promtech on a bacterial genome assembly which is at the supercontig level. However I am getting the following error:

```bash
python ./promotech.py -pg -m RF-HOT -f ../../g4promfinder/Tenacibaculum_caenipelagi_gca_004363005.fa -o results
```

```bash

          PROMOTECH
          MODE         : COMMAND-LINE
          ML MODEL     : FASTA FILE
          INPUT TYPE   : RF-HOT
          INPUT        : ['../../g4promfinder/Tenacibaculum_caenipelagi_gca_004363005.fa']
          TEST SAMPLES : None



 CREATING OUTPUT FOLDER: results


 PRINTING CONTENT
1. GENOME: Ga0244623_101 - LENGTH: 778492
2. GENOME: Ga0244623_102 - LENGTH: 641036
3. GENOME: Ga0244623_103 - LENGTH: 459598
4. GENOME: Ga0244623_104 - LENGTH: 454509
5. GENOME: Ga0244623_105 - LENGTH: 413115
6. GENOME: Ga0244623_106 - LENGTH: 258578
7. GENOME: Ga0244623_107 - LENGTH: 240538
8. GENOME: Ga0244623_108 - LENGTH: 5686
9. GENOME: Ga0244623_109 - LENGTH: 4180
10. GENOME: Ga0244623_110 - LENGTH: 3855
11. GENOME: Ga0244623_111 - LENGTH: 2284
12. GENOME: Ga0244623_112 - LENGTH: 2045
13. GENOME: Ga0244623_113 - LENGTH: 1755
14. GENOME: Ga0244623_114 - LENGTH: 1100


 JOINING ALL CHROMS AND SEQS INTO A SINGLE FOR TETRA-NUCLEOTIDE SLIDING WINDOW


 JOINED GENOME: Ga0244623_101,Ga0244623_102,Ga0244623_103,Ga0244623_104,Ga0244623_105,Ga0244623_106,Ga0244623_107,Ga0244623_108,Ga0244623_109,Ga0244623_110,Ga0244623_111,Ga0244623_112,Ga0244623_113,Ga0244623_114 - LENGTH: 3,266,771


 GENERATING PROMOTER SEQUENCES WITH WINDOW-SIZE: 40 AND STEP: 1. EXPECTED SAMPLES: 3,266,730


100% (3266730 of 3266730) |######################################################################################################| Elapsed Time: 0:00:18 Time:  0:00:18

         TIME ELAPSED FROM START (HOUR:MIN:SEC): 00:00:21


 CUTTED 40 NT SEQUENCES GENERATED SUCCESSFULLY. # OF SAMPLES: 3,266,730 = (3266730,).
        SAMPLE #1: TTTCTTATCGTATCTTAAACCCTATTTTAATGAACTCTTG
        SAMPLE #2: TTCTTATCGTATCTTAAACCCTATTTTAATGAACTCTTGC


 CONVERTING 3266730 CUTTED 40 NT SEQUENCES TO RF-HOT SEQUENCES USING MAPPING VALUES

        [{'A': array([1., 0., 0., 0.])}, {'G': array([0., 1., 0., 0.])}, {'C': array([0., 0., 1., 0.])}, {'T': array([0., 0., 0., 1.])}]


 CONVERTING DATA
 22% (733639 of 3266730) |#######################                                                                                | Elapsed Time: 0:05:03 ETA:   0:16:50Traceback (most recent call last):
  File "./promotech.py", line 83, in <module>
    data_type        = args.model,
  File "/mnt/d/g4_projects/Tenacibaculum_paper_data/results/promtech/Promotech/genome/process_genome.py", line 92, in parseGenome40NTSequences
    X = dataConverter( seqs=cutted_seqs, data_type=data_type, tokenizer_path=tokenizer_path, print_fn=print_fn, log_file=log_file )
  File "/mnt/d/g4_projects/Tenacibaculum_paper_data/results/promtech/Promotech/sequences/../core/utils.py", line 232, in dataConverter
    data_df = fastaToHotEncodingSequences( seqs )
  File "/mnt/d/g4_projects/Tenacibaculum_paper_data/results/promtech/Promotech/sequences/../core/utils.py", line 174, in fastaToHotEncodingSequences
    data = getHotFeatures(seqs)
  File "/mnt/d/g4_projects/Tenacibaculum_paper_data/results/promtech/Promotech/sequences/../core/utils.py", line 168, in getHotFeatures
    data[i, :] = sequenceToBinary(seq)
ValueError: could not broadcast input array from shape (40) into shape (160)
```

Can you explain me how can I prevent this error?

EDIT1: You would also like to change the following in your code

```bash
ML MODEL     : FASTA FILE
INPUT TYPE   : RF-HOT
```
I reran the above code but this time with another model `-m GRU` and it ran successfully

```bash
python ./promotech.py -pg -m GRU -f ../../g4promfinder/Ten
acibaculum_caenipelagi_gca_004363005.fa -o results
```
But it hangs after 99%

PS: I have a laptop with 8GB RAM, ~250 GB SDD and 1TB HDD, 2 cores i3 processor.

**Comment by Rohit-Satyam** [comment]
When I run the second step, I get the following error

```bash
          PROMOTECH
          MODE         : COMMAND-LINE
          ML MODEL     : 40NT SEQUENCE
          INPUT TYPE   : GRU
          INPUT        : None
          TEST SAMPLES : None



 LOADING MACHINE LEARNING MODEL AT: models/GRU-0.h5 WITH SIZE: 0.87 MB
Traceback (most recent call last):
  File "./promotech.py", line 91, in <module>
    threshold       = args.threshold
  File "/mnt/d/g4_projects/Tenacibaculum_paper_data/results/promtech/Promotech/genome/process_genome.py", line 185, in predictGenomeSequences
    model = tf.keras.models.load_model(model_path)
NameError: name 'tf' is not defined
```
It seems like to forgot to mention `import tensorflow as tf` in process_genome.py

**Comment by Rohit-Satyam** [comment]
I now have a new error after correcting for tenserflow error:

```bash

          PROMOTECH
          MODE         : COMMAND-LINE
          ML MODEL     : 40NT SEQUENCE
          INPUT TYPE   : GRU
          INPUT        : None
          TEST SAMPLES : None



 LOADING MACHINE LEARNING MODEL AT: models/GRU-0.h5 WITH SIZE: 0.87 MB


<tensorflow.python.keras.engine.sequential.Sequential object at 0x7fd6affb5f28>



         TIME ELAPSED FROM START (HOUR:MIN:SEC): 00:00:02


 LOADING FORWARD STRAND SEQUENCES CONVERTED TO HOT-ENCODED SEQUENCES: /mnt/d/g4_projects/Tenacibaculum_paper_data/results/promtech/Promotech/results/GRU.data WITH SIZE: 1,933.91 MB


 LOADING INVERSE STRAND SEQUENCES CONVERTED TO HOT-ENCODED SEQUENCES AT: /mnt/d/g4_projects/Tenacibaculum_paper_data/results/promtech/Promotech/results/GRU-INV.data WITH SIZE: 1,933.91 MB


 FORWARD STRAND SEQS: (3266730, 37)
INVERSE STRAND SEQS: (3266730, 37)
ML-MODEL:

<tensorflow.python.keras.engine.sequential.Sequential object at 0x7fd6affb5f28>

         TIME ELAPSED FROM START (HOUR:MIN:SEC): 00:22:09


 GENERATING PREDICTIONS FOR FORWARD STRAND SEQUENCES WITH SHAPE: (3266730, 37)
Traceback (most recent call last):
  File "./promotech.py", line 91, in <module>
    threshold       = args.threshold
  File "/mnt/d/g4_projects/Tenacibaculum_paper_data/results/promtech/Promotech/genome/process_genome.py", line 206, in predictGenomeSequences
    y_probs = model.predict_proba(X)
  File "/home/rohit/miniconda3/envs/promotech_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 316, in predict_proba
    preds = self.predict(x, batch_size, verbose)
  File "/home/rohit/miniconda3/envs/promotech_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 1013, in predict
    use_multiprocessing=use_multiprocessing)
  File "/home/rohit/miniconda3/envs/promotech_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 498, in predict
    workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
  File "/home/rohit/miniconda3/envs/promotech_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 475, in _model_iteration
    total_epochs=1)
  File "/home/rohit/miniconda3/envs/promotech_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/rohit/miniconda3/envs/promotech_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "/home/rohit/miniconda3/envs/promotech_env/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/rohit/miniconda3/envs/promotech_env/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 606, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/rohit/miniconda3/envs/promotech_env/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2363, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/rohit/miniconda3/envs/promotech_env/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "/home/rohit/miniconda3/envs/promotech_env/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/rohit/miniconda3/envs/promotech_env/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/home/rohit/miniconda3/envs/promotech_env/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  indices[8,36] = -2147483648 is not in [0, 466)
         [[node sequential_10/embedding_10/embedding_lookup (defined at /mnt/d/g4_projects/Tenacibaculum_paper_data/results/promtech/Promotech/genome/process_genome.py:206) ]] [Op:__inference_distributed_function_3937]

Errors may have originated from an input operation.
Input Source operations connected to node sequential_10/embedding_10/embedding_lookup:
 sequential_10/embedding_10/embedding_lookup/3646 (defined at /home/rohit/miniconda3/envs/promotech_env/lib/python3.6/contextlib.py:81)

Function call stack:
distributed_function
```

**Comment by Rohit-Satyam** [comment]
I also tried running the second step on the workstation with the following configuration but the error persists

```bash
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              20
On-line CPU(s) list: 0-19
Thread(s) per core:  2
Core(s) per socket:  10
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) W-2255 CPU @ 3.70GHz
Stepping:            7
CPU MHz:             1295.346
CPU max MHz:         3701.0000
CPU min MHz:         1200.0000
BogoMIPS:            7399.70
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            19712K
NUMA node0 CPU(s):   0-19
```

**Comment by BioinformaticsLabAtMUN** [comment]
Hello  Rohit-Satyam,

On which operating system are you running Promotech? and what Python version are you using?

Thank you!

**Comment by ramostapiai** [comment]
> Hi Developers!!
> 
> I planned using Promtech on a bacterial genome assembly which is at the supercontig level. However I am getting the following error:
> 
> ```shell
> python ./promotech.py -pg -m RF-HOT -f ../../g4promfinder/Tenacibaculum_caenipelagi_gca_004363005.fa -o results
> ```
> 
> ```shell
>           PROMOTECH
>           MODE         : COMMAND-LINE
>           ML MODEL     : FASTA FILE
>           INPUT TYPE   : RF-HOT
>           INPUT        : ['../../g4promfinder/Tenacibaculum_caenipelagi_gca_004363005.fa']
>           TEST SAMPLES : None
> 
> 
> 
>  CREATING OUTPUT FOLDER: results
> 
> 
>  PRINTING CONTENT
> 1. GENOME: Ga0244623_101 - LENGTH: 778492
> 2. GENOME: Ga0244623_102 - LENGTH: 641036
> 3. GENOME: Ga0244623_103 - LENGTH: 459598
> 4. GENOME: Ga0244623_104 - LENGTH: 454509
> 5. GENOME: Ga0244623_105 - LENGTH: 413115
> 6. GENOME: Ga0244623_106 - LENGTH: 258578
> 7. GENOME: Ga0244623_107 - LENGTH: 240538
> 8. GENOME: Ga0244623_108 - LENGTH: 5686
> 9. GENOME: Ga0244623_109 - LENGTH: 4180
> 10. GENOME: Ga0244623_110 - LENGTH: 3855
> 11. GENOME: Ga0244623_111 - LENGTH: 2284
> 12. GENOME: Ga0244623_112 - LENGTH: 2045
> 13. GENOME: Ga0244623_113 - LENGTH: 1755
> 14. GENOME: Ga0244623_114 - LENGTH: 1100
> 
> 
>  JOINING ALL CHROMS AND SEQS INTO A SINGLE FOR TETRA-NUCLEOTIDE SLIDING WINDOW
> 
> 
>  JOINED GENOME: Ga0244623_101,Ga0244623_102,Ga0244623_103,Ga0244623_104,Ga0244623_105,Ga0244623_106,Ga0244623_107,Ga0244623_108,Ga0244623_109,Ga0244623_110,Ga0244623_111,Ga0244623_112,Ga0244623_113,Ga0244623_114 - LENGTH: 3,266,771
> 
> 
>  GENERATING PROMOTER SEQUENCES WITH WINDOW-SIZE: 40 AND STEP: 1. EXPECTED SAMPLES: 3,266,730
> 
> 
> 100% (3266730 of 3266730) |######################################################################################################| Elapsed Time: 0:00:18 Time:  0:00:18
> 
>          TIME ELAPSED FROM START (HOUR:MIN:SEC): 00:00:21
> 
> 
>  CUTTED 40 NT SEQUENCES GENERATED SUCCESSFULLY. # OF SAMPLES: 3,266,730 = (3266730,).
>         SAMPLE #1: TTTCTTATCGTATCTTAAACCCTATTTTAATGAACTCTTG
>         SAMPLE #2: TTCTTATCGTATCTTAAACCCTATTTTAATGAACTCTTGC
> 
> 
>  CONVERTING 3266730 CUTTED 40 NT SEQUENCES TO RF-HOT SEQUENCES USING MAPPING VALUES
> 
>         [{'A': array([1., 0., 0., 0.])}, {'G': array([0., 1., 0., 0.])}, {'C': array([0., 0., 1., 0.])}, {'T': array([0., 0., 0., 1.])}]
> 
> 
>  CONVERTING DATA
>  22% (733639 of 3266730) |#######################                                                                                | Elapsed Time: 0:05:03 ETA:   0:16:50Traceback (most recent call last):
>   File "./promotech.py", line 83, in <module>
>     data_type        = args.model,
>   File "/mnt/d/g4_projects/Tenacibaculum_paper_data/results/promtech/Promotech/genome/process_genome.py", line 92, in parseGenome40NTSequences
>     X = dataConverter( seqs=cutted_seqs, data_type=data_type, tokenizer_path=tokenizer_path, print_fn=print_fn, log_file=log_file )
>   File "/mnt/d/g4_projects/Tenacibaculum_paper_data/results/promtech/Promotech/sequences/../core/utils.py", line 232, in dataConverter
>     data_df = fastaToHotEncodingSequences( seqs )
>   File "/mnt/d/g4_projects/Tenacibaculum_paper_data/results/promtech/Promotech/sequences/../core/utils.py", line 174, in fastaToHotEncodingSequences
>     data = getHotFeatures(seqs)
>   File "/mnt/d/g4_projects/Tenacibaculum_paper_data/results/promtech/Promotech/sequences/../core/utils.py", line 168, in getHotFeatures
>     data[i, :] = sequenceToBinary(seq)
> ValueError: could not broadcast input array from shape (40) into shape (160)
> ```
> 
> Can you explain me how can I prevent this error?
> 
> EDIT1: You would also like to change the following in your code
> 
> ```shell
> ML MODEL     : FASTA FILE
> INPUT TYPE   : RF-HOT
> ```
> 
> I reran the above code but this time with another model `-m GRU` and it ran successfully
> 
> ```shell
> python ./promotech.py -pg -m GRU -f ../../g4promfinder/Ten
> acibaculum_caenipelagi_gca_004363005.fa -o results
> ```
> 
> But it hangs after 99%
> 
> PS: I have a laptop with 8GB RAM, ~250 GB SDD and 1TB HDD, 2 cores i3 processor.

I have the same error when a run the code  "python promotech.py -pg -g -m RF-HOT -f GCF_000008565.fasta -o results"
I using a MacOS with python 3.6.10.
I have a laptop with 64GB RAM, ~1 TB SDD , 8 cores i9 processor
