### ISSUE TITLE
Issue with reading a long sequence using the whole genome method

### ISSUE THREAD

**Issue by vmreyes12** [BioinformaticsLabAtMUN/Promotech#7]
Hello!
The tool is installed correctly and runs through the example scenarios fine. I'm on a ubuntu 20.04. However, when I try to run the tool over a 29.5kb segment of DNA, I get an error as follows:

```
`CONVERTING 29563 CUTTED 40 NT SEQUENCES TO RF-HOT SEQUENCES USING MAPPING VALUES 

	[{'A': array([1., 0., 0., 0.])}, {'G': array([0., 1., 0., 0.])}, {'C': array([0., 0., 1., 0.])}, {'T': array([0., 0., 0., 1.])}]


 CONVERTING DATA
Traceback (most recent call last):
  File "promotech.py", line 83, in <module>
    data_type        = args.model,
  File "/home/user/PromoTech/genome/process_genome.py", line 92, in parseGenome40NTSequences
    X = dataConverter( seqs=cutted_seqs, data_type=data_type, tokenizer_path=tokenizer_path, print_fn=print_fn, log_file=log_file )
  File "/home/user/PromoTech/sequences/../core/utils.py", line 232, in dataConverter
    data_df = fastaToHotEncodingSequences( seqs )
  File "/home/user/PromoTech/sequences/../core/utils.py", line 174, in fastaToHotEncodingSequences
    data = getHotFeatures(seqs)
  File "/home/user/PromoTech/sequences/../core/utils.py", line 168, in getHotFeatures
    data[i, :] = sequenceToBinary(seq)
ValueError: could not broadcast input array from shape (40) into shape (160)
```
`
Any advice as to how to solve this error would be greatly appreciated.

**Comment by BioinformaticsLabAtMUN** [comment]
Hello,

Make sure you input sequence only contains A, C, G and T. Promotech will fail with any other character.

**Comment by liampshaw** [comment]
In case it is of use to others, I use a hack to allow one to parse an input sequence with ambiguous characters, without checking the sequence first. 

I've made a fork of the repo that sets any 40nt sequence containing ambiguous characters to poly-A: `AAA...AAA` and warns that this has been done. This means these sequences will get a score (under RF-HOT model) of 0.0943. This is a fake score (ideally one would set to `NA` or missing) but if using default threshold of 0.5 one will not see these fake predictions. 

It's a small change in `core/utils.py`, available at https://github.com/liampshaw/Promotech/tree/feat/handle_ambiguous. 

Here is the `diff`:

```
160a161
>   warned_ambiguous = False
168c169,177
<     data[i, :] = sequenceToBinary(seq)
---
>     # Only accept ATCG sequences i.e. no ambiguity
>     seq_clean = "".join([x for x in seq if x in ["A", "T", "C", "G"]])
>     if len(seq_clean)<40: # if ambiguous bases, set seq="A"x40 (score in RF-HOT of 0.09243)
>       seq_clean = "".join(["A" for x in range(40)])
>       if warned_ambiguous==False:
>         print("\n  WARNING: your sequence contained ambiguous bases.\n  These were set to AAA...AAA (RF-HOT score: 0.0943) for convenience.\n  For your information, here is the first sequence encountered:\n  "+seq+"\n")
>         print("  (will not warn again for future occurrences of ambiguous bases)\n")
>         warned_ambiguous = True
>     data[i, :] = sequenceToBinary(seq_clean)
```
